# Generated by Django 3.1.1 on 2021-07-18 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_info', models.FileField(upload_to='file_knowledge_base')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='gambar',
            field=models.ImageField(blank=True, null=True, upload_to='gambar_knowledge_base'),
        ),
        migrations.AddField(
            model_name='post',
            name='file',
            field=models.ManyToManyField(to='knowledge_base.FilePost'),
        ),
    ]
