# Generated by Django 3.1.1 on 2021-07-21 11:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0005_auto_20210718_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tautan_youtube',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
