# Generated by Django 3.1.1 on 2021-07-23 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0006_post_tautan_youtube'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tautan_youtube',
            field=models.TextField(blank=True, null=True),
        ),
    ]
