# Generated by Django 3.1.1 on 2021-05-25 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_kontrak', '0005_auto_20210525_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lampirankontrak',
            name='kuantitas',
            field=models.FloatField(),
        ),
    ]
