# Generated by Django 3.1.1 on 2021-06-04 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_kontrak', '0009_auto_20210604_0536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kontrak',
            name='unit_kerja',
        ),
        migrations.DeleteModel(
            name='Bagian',
        ),
    ]
