# Generated by Django 3.1.1 on 2021-07-08 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PegawaiBersertifikat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('nip', models.CharField(max_length=18)),
                ('email', models.EmailField(max_length=254)),
                ('jenis_sertifikat', models.CharField(choices=[('Tingkat Dasar', 'tingkat dasar'), ('Standar Kompetensi Level 1', 'kompetensi level 1'), ('Standar Kompetensi Level 2', 'kompetensi level 2'), ('Standar Kompetensi Level 3', 'kompetensi level 3'), ('Lainnya', 'lainnya')], default='Tingkat Dasar', max_length=100)),
            ],
        ),
    ]
