# Generated by Django 3.1.1 on 2021-07-08 14:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_ukpbj', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pegawaibersertifikat',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pegawaibersertifikat',
            name='file_sertifikat',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='sertifikat_pbj/'),
        ),
    ]
