# Generated by Django 3.1.1 on 2021-07-08 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_ukpbj', '0002_auto_20210708_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='pegawaibersertifikat',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
