# Generated by Django 3.1.1 on 2021-07-08 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_ukpbj', '0003_pegawaibersertifikat_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='pegawaibersertifikat',
            name='nomor_hp',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
