# Generated by Django 3.1.1 on 2021-07-08 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_ukpbj', '0005_pegawaibersertifikat_nomor_sertifikat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pegawaibersertifikat',
            name='nomor_hp',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
