# Generated by Django 3.1.1 on 2021-07-09 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_ukpbj', '0006_auto_20210708_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='pegawaibersertifikat',
            name='foto',
            field=models.ImageField(blank=True, default='profilepics/avatar.jpeg', null=True, upload_to='profilepics'),
        ),
    ]
