# Generated by Django 3.1.1 on 2021-07-12 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_ukpbj', '0007_pegawaibersertifikat_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='pegawaibersertifikat',
            name='status_kepegawaian',
            field=models.CharField(default='Aktif', max_length=100),
        ),
        migrations.AddField(
            model_name='pegawaibersertifikat',
            name='tanggal_sertifikat',
            field=models.DateField(blank=True, null=True),
        ),
    ]
