# Generated by Django 3.1.1 on 2021-07-12 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_ukpbj', '0008_auto_20210712_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pegawaibersertifikat',
            name='status_kepegawaian',
            field=models.CharField(choices=[('Aktif', 'aktif'), ('Pensiun', 'pensiun')], default='Aktif', max_length=100),
        ),
        migrations.CreateModel(
            name='PokjaPemilihan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_sk_pokja', models.CharField(blank=True, max_length=100, null=True)),
                ('keterangan', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('nama_pegawai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manajemen_ukpbj.pegawaibersertifikat')),
            ],
        ),
    ]
