# Generated by Django 3.1.1 on 2021-07-12 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_ukpbj', '0009_auto_20210712_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokjapemilihan',
            name='keterangan',
            field=models.TextField(blank=True, null=True),
        ),
    ]
