# Generated by Django 3.1.1 on 2021-07-12 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_ukpbj', '0010_auto_20210712_0920'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PokjaPemilihan',
        ),
    ]
