# Generated by Django 3.1.1 on 2021-07-12 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_ukpbj', '0012_auto_20210712_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skpokjapemilihan',
            name='keterangan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='skpokjapemilihan',
            name='tanggal_sk',
            field=models.DateField(),
        ),
    ]
