# Generated by Django 3.1.1 on 2021-07-12 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_ukpbj', '0014_skpokjapemilihan_nomor_sk'),
    ]

    operations = [
        migrations.AddField(
            model_name='skpokjapemilihan',
            name='file_sk',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
