# Generated by Django 3.1.1 on 2021-07-12 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_ukpbj', '0015_skpokjapemilihan_file_sk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pegawaibersertifikat',
            name='sk_pokja',
        ),
    ]
