# Generated by Django 3.1.1 on 2021-07-12 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_ukpbj', '0016_remove_pegawaibersertifikat_sk_pokja'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pegawaibersertifikat',
            name='sebagai_pokja_pemilihan',
        ),
    ]
