# Generated by Django 3.1.1 on 2021-07-12 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_ukpbj', '0017_remove_pegawaibersertifikat_sebagai_pokja_pemilihan'),
    ]

    operations = [
        migrations.AddField(
            model_name='pegawaibersertifikat',
            name='sebagai_pokja_pemilihan',
            field=models.BooleanField(default=False),
        ),
    ]
