# Generated by Django 3.1.1 on 2021-07-12 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_ukpbj', '0018_pegawaibersertifikat_sebagai_pokja_pemilihan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pegawaibersertifikat',
            name='sebagai_pokja_pemilihan',
            field=models.CharField(choices=[('Ya', 'ya'), ('Tidak', 'tidak')], default='Tidak', max_length=100),
        ),
    ]
