# Generated by Django 3.1.1 on 2021-07-12 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_ukpbj', '0023_auto_20210712_1042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pegawaibersertifikat',
            name='sk_pokja',
        ),
    ]
