# Generated by Django 3.1.1 on 2021-07-12 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_ukpbj', '0027_auto_20210712_1053'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PegawaiBersertifikat',
        ),
        migrations.DeleteModel(
            name='SkPokjaPemilihan',
        ),
    ]
