# Generated by Django 3.1.1 on 2021-07-12 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manajemen_ukpbj', '0028_auto_20210712_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkPokjaPemilihan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_sk', models.CharField(default='Nomor 23/HUK/2020', max_length=200)),
                ('judul_sk', models.CharField(max_length=250)),
                ('tanggal_sk', models.DateField()),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('file_sk', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='PegawaiBersertifikat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('status_kepegawaian', models.CharField(choices=[('Aktif', 'aktif'), ('Pensiun', 'pensiun')], default='Aktif', max_length=100)),
                ('nip', models.CharField(max_length=18)),
                ('email', models.EmailField(max_length=254)),
                ('nomor_hp', models.CharField(blank=True, max_length=13, null=True)),
                ('nomor_sertifikat', models.CharField(blank=True, max_length=100, null=True)),
                ('jenis_sertifikat', models.CharField(choices=[('Tingkat Dasar', 'tingkat dasar'), ('Standar Kompetensi Level 1', 'kompetensi level 1'), ('Standar Kompetensi Level 2', 'kompetensi level 2'), ('Standar Kompetensi Level 3', 'kompetensi level 3'), ('Lainnya', 'lainnya')], default='Tingkat Dasar', max_length=100)),
                ('tanggal_sertifikat', models.DateField(blank=True, null=True)),
                ('file_sertifikat', models.FileField(blank=True, max_length=255, null=True, upload_to='sertifikat_pbj/')),
                ('foto', models.ImageField(blank=True, default='profilepics/avatar.jpeg', null=True, upload_to='profilepics')),
                ('sebagai_pokja_pemilihan', models.CharField(choices=[('Tidak', 'tidak'), ('Ya', 'ya')], default='Tidak', max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('sk_pokja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manajemen_ukpbj.skpokjapemilihan')),
            ],
        ),
    ]
