# Generated by Django 3.1.1 on 2021-07-12 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_ukpbj', '0030_auto_20210712_1111'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuratTugas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('tanggal', models.DateField()),
                ('file_surat_tugas', models.FileField(upload_to='surat_tugas_pokja/')),
            ],
        ),
        migrations.AlterField(
            model_name='skpokjapemilihan',
            name='file_sk',
            field=models.FileField(blank=True, null=True, upload_to='file_sk/'),
        ),
    ]
