# Generated by Django 3.1.1 on 2021-07-12 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_ukpbj', '0032_auto_20210712_1430'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaketPekerjaan',
        ),
    ]
