# Generated by Django 3.1.1 on 2021-07-12 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_ukpbj', '0034_paketpekerjaan'),
    ]

    operations = [
        migrations.AddField(
            model_name='paketpekerjaan',
            name='dokumen_surat_usulan',
            field=models.FileField(blank=True, null=True, upload_to='dokumen_surat_usulan'),
        ),
        migrations.AddField(
            model_name='paketpekerjaan',
            name='nomor_surat_usulan_tender',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
