# Generated by Django 3.1.1 on 2021-07-12 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_ukpbj', '0035_auto_20210712_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='paketpekerjaan',
            name='tanggal_surat_tugas',
            field=models.DateField(auto_now=True),
        ),
    ]
