# Generated by Django 3.1.1 on 2021-07-12 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_ukpbj', '0036_paketpekerjaan_tanggal_surat_tugas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paketpekerjaan',
            name='tanggal_surat_tugas',
            field=models.DateField(),
        ),
    ]
