# Generated by Django 3.1.1 on 2021-07-12 14:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_ukpbj', '0037_auto_20210712_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='paketpekerjaan',
            name='tanggal_usulan',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
