# Generated by Django 3.1.1 on 2021-07-12 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_ukpbj', '0040_delete_paketpekerjaan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Satker',
        ),
    ]
