# Generated by Django 3.1.1 on 2021-07-12 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_ukpbj', '0042_satker'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaketPekerjaan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_paket', models.CharField(max_length=250)),
                ('nomor_surat_tugas', models.CharField(max_length=100)),
                ('tanggal_surat_tugas', models.DateField()),
                ('file_surat_tugas', models.FileField(upload_to='surat_tugas_pokja')),
                ('nilai_pagu', models.IntegerField(blank=True, null=True)),
                ('nilai_hps', models.IntegerField(blank=True, null=True)),
                ('dokumen_hps', models.FileField(blank=True, null=True, upload_to='dokumen_hps')),
                ('dokumen_kak_spek', models.FileField(blank=True, null=True, upload_to='dokumen_kak_spek')),
                ('nomor_surat_usulan_tender', models.CharField(blank=True, max_length=200, null=True)),
                ('tanggal_usulan', models.DateField()),
                ('dokumen_surat_usulan', models.FileField(blank=True, null=True, upload_to='dokumen_surat_usulan')),
                ('kode_rup', models.CharField(blank=True, max_length=10, null=True)),
                ('kode_tender', models.CharField(blank=True, max_length=10, null=True)),
                ('pokja_pemilihan', models.ManyToManyField(to='manajemen_ukpbj.PegawaiBersertifikat')),
            ],
        ),
    ]
