# Generated by Django 3.1.1 on 2021-07-12 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_ukpbj', '0045_auto_20210712_1622'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paketpekerjaan',
            old_name='nama_satker',
            new_name='satker_pengguna',
        ),
    ]
