# Generated by Django 3.1.1 on 2021-07-12 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_ukpbj', '0046_auto_20210712_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paketpekerjaan',
            name='nilai_hps',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paketpekerjaan',
            name='nilai_pagu',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
