# Generated by Django 3.1.1 on 2021-07-12 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_ukpbj', '0047_auto_20210712_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='paketpekerjaan',
            name='arsip_dokumen_pengadaan',
            field=models.FileField(blank=True, null=True, upload_to='arsip_dokumen_pengadaan'),
        ),
        migrations.AddField(
            model_name='paketpekerjaan',
            name='status_paket',
            field=models.CharField(choices=[('Persiapan Pengadaan', 'persiapan pengadaan'), ('Proses Tender', 'proses tender'), ('Selesai Tender', 'selesai tender')], default='Persiapan Pengadaan', max_length=100),
        ),
    ]
