# Generated by Django 3.1.1 on 2021-07-12 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_ukpbj', '0048_auto_20210712_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='paketpekerjaan',
            name='nilai_hasil_tender',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
