# Generated by Django 3.1.1 on 2021-07-12 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_ukpbj', '0050_paketpekerjaan_tahun_anggaran'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paketpekerjaan',
            name='tahun_anggaran',
            field=models.CharField(choices=[(2020, 2020), (2021, 2021), (2022, 2022)], default=2021, max_length=4),
        ),
    ]
