# Generated by Django 3.1.1 on 2021-07-12 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_ukpbj', '0052_auto_20210712_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paketpekerjaan',
            name='tahun_anggaran',
            field=models.CharField(choices=[('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025')], default=2021, max_length=4),
        ),
    ]
