# Generated by Django 3.1.1 on 2021-07-12 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_ukpbj', '0053_auto_20210712_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paketpekerjaan',
            name='status_paket',
            field=models.CharField(choices=[('Persiapan Pengadaan', 'persiapan pengadaan'), ('Proses Tender', 'proses tender'), ('Selesai Tender', 'selesai tender'), ('Gagal Tender', 'gagal tender')], default='Persiapan Pengadaan', max_length=100),
        ),
    ]
