# Generated by Django 3.1.1 on 2021-07-13 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_ukpbj', '0055_paketpekerjaan_keterangan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paketpekerjaan',
            name='nomor_surat_usulan_tender',
            field=models.CharField(max_length=200),
        ),
    ]
