# Generated by Django 3.1.1 on 2021-07-13 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_ukpbj', '0056_auto_20210713_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paketpekerjaan',
            name='nomor_surat_usulan_tender',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
