# Generated by Django 3.1.1 on 2021-07-13 18:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_ukpbj', '0057_auto_20210713_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paketpekerjaan',
            name='dokumen_surat_usulan',
            field=models.FileField(default=django.utils.timezone.now, upload_to='dokumen_surat_usulan'),
            preserve_default=False,
        ),
    ]
