# Generated by Django 3.1.1 on 2021-07-13 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_ukpbj', '0059_auto_20210713_1818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paketpekerjaan',
            name='dokumen_surat_usulan',
        ),
        migrations.RemoveField(
            model_name='paketpekerjaan',
            name='nomor_surat_usulan_tender',
        ),
    ]
