# Generated by Django 3.1.1 on 2021-07-13 18:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_ukpbj', '0062_auto_20210713_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paketpekerjaan',
            name='file_surat_tugas',
            field=models.FileField(default=django.utils.timezone.now, upload_to='surat_tugas_pokja'),
            preserve_default=False,
        ),
    ]
