# Generated by Django 3.1.1 on 2021-07-22 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_ukpbj', '0063_auto_20210713_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paketpekerjaan',
            name='status_paket',
            field=models.CharField(choices=[('Persiapan Pengadaan', 'persiapan pengadaan'), ('Proses Tender', 'proses tender'), ('Selesai Tender', 'selesai tender'), ('Gagal Tender', 'gagal tender'), ('Fullboard Meeting', 'fullboard meeting')], default='Persiapan Pengadaan', max_length=100),
        ),
    ]
