# Generated by Django 3.1.1 on 2021-06-09 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_kontrak', '0002_tandaterimadistribusi_catatan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tandaterimadistribusi',
            name='catatan',
        ),
        migrations.AlterField(
            model_name='barang',
            name='satuan',
            field=models.CharField(choices=[('unit', 'unit'), ('buah', 'buah'), ('ls', 'ls'), ('hari', 'hari'), ('m1', 'm1'), ('m2', 'm2'), ('bh', 'bh'), ('meter', 'meter'), ('pcs', 'pcs'), ('buku', 'buku'), ('rim', 'rim'), ('set', 'set'), ('roll', 'roll'), ('minggu', 'minggu'), ('bulan', 'bulan'), ('tahun', 'tahun'), ('lembar', 'lembar'), ('box', 'box')], max_length=100),
        ),
    ]
