# Generated by Django 3.1.1 on 2021-06-24 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_kontrak', '0002_auto_20210624_0523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barang',
            name='satuan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manajemen_kontrak.satuanbarang'),
        ),
    ]
