# Generated by Django 3.1.1 on 2021-04-30 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_kontrak', '0002_barang_fotobarang'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotobarang',
            name='deskripsi',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
