# Generated by Django 3.1.1 on 2021-04-30 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_kontrak', '0003_fotobarang_deskripsi'),
    ]

    operations = [
        migrations.AddField(
            model_name='barang',
            name='keterangan',
            field=models.TextField(blank=True, null=True),
        ),
    ]
