# Generated by Django 3.1.1 on 2021-06-24 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_kontrak', '0003_auto_20210624_0529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barang',
            name='satuan',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manajemen_kontrak.satuanbarang'),
        ),
        migrations.AlterField(
            model_name='satuanbarang',
            name='satuan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
