# Generated by Django 3.1.1 on 2021-05-20 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_kontrak', '0003_tandaterimadistribusi_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tandaterimadistribusi',
            name='created_by',
        ),
    ]
