# Generated by Django 3.1.1 on 2021-05-28 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_kontrak', '0004_remove_tandaterimadistribusi_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barang',
            name='satuan',
            field=models.CharField(choices=[('unit', 'unit'), ('buah', 'buah'), ('ls', 'ls'), ('hari', 'hari'), ('m1', 'm1'), ('m2', 'm2'), ('bh', 'bh'), ('meter', 'meter'), ('pcs', 'pcs'), ('buku', 'buku'), ('rim', 'rim'), ('set', 'set'), ('roll', 'roll'), ('minggu', 'minggu'), ('bulan', 'bulan'), ('tahun', 'tahun')], max_length=100),
        ),
        migrations.AlterField(
            model_name='kontrak',
            name='kode_kegiatan_output_akun',
            field=models.CharField(default='2228.962.004/052/A/532111', max_length=50),
        ),
        migrations.AlterField(
            model_name='kontrak',
            name='nomor_dipa',
            field=models.CharField(default='027.01.1.440121/2020', max_length=500),
        ),
        migrations.AlterField(
            model_name='kontrak',
            name='tanggal_dipa',
            field=models.DateField(default='2019-11-21'),
        ),
        migrations.AlterField(
            model_name='lampirankontrak',
            name='kuantitas',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
