# Generated by Django 3.1.1 on 2021-06-02 09:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_kontrak', '0005_auto_20210528_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotoitempekerjaan',
            name='file_foto',
            field=models.ImageField(blank=True, null=True, upload_to='foto_pekerjaan'),
        ),
        migrations.AlterField(
            model_name='kontrak',
            name='dokumen_pengadaan',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='dokumenpengadaan/'),
        ),
        migrations.AlterField(
            model_name='kontrak',
            name='nomor_kontrak',
            field=models.CharField(default='.../1.5/PL.02.01/6/2021', max_length=200),
        ),
        migrations.AlterField(
            model_name='useradmin',
            name='profil_pic',
            field=models.ImageField(blank=True, default='profile.png', null=True, upload_to='profilepics'),
        ),
        migrations.CreateModel(
            name='PemeriksaanBarang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul_pemeriksaan', models.CharField(blank=True, max_length=250, null=True)),
                ('tanggal_pemeriksaan', models.DateTimeField(default=datetime.date.today)),
                ('catatan', models.TextField(blank=True, null=True)),
                ('berkas_pemeriksaan', models.FileField(blank=True, null=True, upload_to='berkas_pemeriksaan')),
                ('item_pekerjaan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manajemen_kontrak.lampirankontrak')),
            ],
        ),
    ]
