# Generated by Django 3.1.1 on 2021-06-03 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_kontrak', '0005_auto_20210528_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotoitempekerjaan',
            name='file_foto',
            field=models.ImageField(blank=True, null=True, upload_to='foto_pekerjaan'),
        ),
        migrations.AlterField(
            model_name='kontrak',
            name='dokumen_pengadaan',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='dokumenpengadaan/'),
        ),
        migrations.AlterField(
            model_name='kontrak',
            name='nomor_kontrak',
            field=models.CharField(default='.../1.5/PL.02.01/6/2021', max_length=200),
        ),
        migrations.AlterField(
            model_name='useradmin',
            name='profil_pic',
            field=models.ImageField(blank=True, default='profile.png', null=True, upload_to='profilepics'),
        ),
    ]
