# Generated by Django 3.1.1 on 2021-05-01 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_kontrak', '0005_penyedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barang',
            name='satuan',
            field=models.CharField(choices=[('unit', 'unit'), ('buah', 'buah')], max_length=100),
        ),
    ]
