# Generated by Django 3.1.1 on 2021-06-03 14:29

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manajemen_kontrak', '0007_auto_20210603_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barang',
            name='satuan',
            field=models.CharField(choices=[('unit', 'unit'), ('buah', 'buah'), ('ls', 'ls'), ('hari', 'hari'), ('m1', 'm1'), ('m2', 'm2'), ('bh', 'bh'), ('meter', 'meter'), ('pcs', 'pcs'), ('buku', 'buku'), ('rim', 'rim'), ('set', 'set'), ('roll', 'roll'), ('minggu', 'minggu'), ('bulan', 'bulan'), ('tahun', 'tahun')], max_length=100),
        ),
        migrations.AlterField(
            model_name='fotoitempekerjaan',
            name='file_foto',
            field=models.ImageField(blank=True, null=True, upload_to='foto_pekerjaan'),
        ),
        migrations.AlterField(
            model_name='kontrak',
            name='dokumen_pengadaan',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='dokumenpengadaan/'),
        ),
        migrations.AlterField(
            model_name='lampirankontrak',
            name='kuantitas',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='tandaterimadistribusi',
            name='file_tanda_terima',
            field=models.FileField(blank=True, null=True, upload_to='tanda_terima_distribusi'),
        ),
        migrations.AlterField(
            model_name='useradmin',
            name='profil_pic',
            field=models.ImageField(blank=True, default='profilepics/avatar.jpeg', null=True, upload_to='profilepics'),
        ),
        migrations.CreateModel(
            name='PemeriksaanBarang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_pemeriksaan', models.DateField(default=datetime.datetime.now)),
                ('catatan', models.TextField(blank=True, null=True)),
                ('berkas_pemeriksaan', models.FileField(blank=True, null=True, upload_to='berkas_pemeriksaan')),
                ('item_pekerjaan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manajemen_kontrak.lampirankontrak')),
                ('user_pemeriksa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
