# Generated by Django 3.1.1 on 2021-05-02 04:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_kontrak', '0007_auto_20210502_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='kontrak',
            name='tanggal_kontrak',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
