# Generated by Django 3.1.1 on 2021-06-02 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_kontrak', '0007_auto_20210602_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pemeriksaanbarang',
            name='judul_pemeriksaan',
        ),
    ]
