# Generated by Django 3.1.1 on 2021-06-04 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_kontrak', '0008_auto_20210603_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bagian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_bagian', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='kontrak',
            name='unit_kerja',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manajemen_kontrak.bagian'),
        ),
    ]
