# Generated by Django 3.1.1 on 2021-06-02 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_kontrak', '0008_remove_pemeriksaanbarang_judul_pemeriksaan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pemeriksaanbarang',
            name='item_pekerjaan',
        ),
    ]
