# Generated by Django 3.1.1 on 2021-05-02 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_kontrak', '0009_auto_20210502_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='kontrak',
            name='cara_pembayaran',
            field=models.CharField(choices=[('Bulanan', 'Bulanan'), ('Bertahap/Termin', 'Bertahap/Termin'), ('Sekaligus', 'Sekaligus')], default='Sekaligus', max_length=200),
        ),
        migrations.AddField(
            model_name='kontrak',
            name='nilai_kontrak_terbilang',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
