# Generated by Django 3.1.1 on 2021-06-02 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_kontrak', '0009_remove_pemeriksaanbarang_item_pekerjaan'),
    ]

    operations = [
        migrations.AddField(
            model_name='pemeriksaanbarang',
            name='item_pekerjaan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manajemen_kontrak.lampirankontrak'),
        ),
    ]
