# Generated by Django 3.1.1 on 2021-05-02 04:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_kontrak', '0010_auto_20210502_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='kontrak',
            name='tanggal_berakhir_kontrak',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='kontrak',
            name='kode_kegiatan_output_akun',
            field=models.CharField(default='2228 / 995 / 532111', max_length=50),
        ),
    ]
