# Generated by Django 3.1.1 on 2021-05-02 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_kontrak', '0011_auto_20210502_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='kontrak',
            name='ketentuan_sanksi',
            field=models.CharField(blank=True, default='Denda 1 ‰ untuk setiap hari keterlambatan dari biaya / harga keseluruhan (sebelum PPn)', max_length=500, null=True),
        ),
    ]
