# Generated by Django 3.1.1 on 2021-06-02 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_kontrak', '0012_remove_pemeriksaanbarang_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pemeriksaanbarang',
            name='berkas_pemeriksaan',
        ),
        migrations.RemoveField(
            model_name='pemeriksaanbarang',
            name='item_pekerjaan',
        ),
    ]
