# Generated by Django 3.1.1 on 2021-05-02 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_kontrak', '0012_kontrak_ketentuan_sanksi'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Kontrak',
        ),
    ]
