# Generated by Django 3.1.1 on 2021-06-02 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_kontrak', '0013_auto_20210602_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='pemeriksaanbarang',
            name='berkas_pemeriksaan',
            field=models.FileField(blank=True, null=True, upload_to='berkas_pemeriksaan'),
        ),
    ]
