# Generated by Django 3.1.1 on 2021-05-02 04:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_kontrak', '0013_delete_kontrak'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kontrak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_dipa', models.CharField(max_length=500)),
                ('tanggal_dipa', models.DateField(default=datetime.datetime.now)),
                ('nomor_kontrak', models.CharField(max_length=200)),
                ('judul_kontrak', models.CharField(max_length=500)),
                ('tanggal_kontrak', models.DateField(default=datetime.datetime.now)),
                ('tanggal_berakhir_kontrak', models.DateField(default=datetime.datetime.now)),
                ('kode_kegiatan_output_akun', models.CharField(default='2228 / 995 / 532111', max_length=50)),
                ('jenis_pekerjaan', models.CharField(choices=[('pengadaan barang', 'pengadaan barang'), ('pekerjaan konstruksi', 'pekerjaan konstruksi'), ('jasa konsultan', 'jasa konsultan'), ('jasa lainnya', 'jasa lainnya')], default='pengadaan barang', max_length=100)),
                ('bentuk_kontrak', models.CharField(choices=[('Surat Perjanjian (kontrak)', 'Surat Perjanjian (kontrak)'), ('Surat Perintah Kerja', 'Surat Perintah Kerja'), ('Kuitansi', 'Kuitansi'), ('Surat Pesanan', 'Surat Pesanan'), ('Bukti Pembelian', 'Bukti Pembelian')], default='Surat Perintah Kerja', max_length=100)),
                ('nilai_kontrak_terbilang', models.CharField(blank=True, max_length=200, null=True)),
                ('cara_pembayaran', models.CharField(choices=[('Bulanan', 'Bulanan'), ('Bertahap/Termin', 'Bertahap/Termin'), ('Sekaligus', 'Sekaligus')], default='Sekaligus', max_length=200)),
                ('ketentuan_sanksi', models.CharField(blank=True, default='Denda 1 ‰ untuk setiap hari keterlambatan dari biaya / harga keseluruhan (sebelum PPn)', max_length=500, null=True)),
            ],
        ),
    ]
