# Generated by Django 3.1.1 on 2021-05-02 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_kontrak', '0014_kontrak'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kontrak',
            name='jenis_pekerjaan',
            field=models.CharField(choices=[('Pengadaan Barang', 'Pengadaan Barang'), ('Pekerjaan Konstruksi', 'Pekerjaan Konstruksi'), ('Jasa konsultan', 'Jasa konsultan'), ('Jasa lainnya', 'Jasa lainnya')], default='pengadaan barang', max_length=100),
        ),
        migrations.AlterField(
            model_name='kontrak',
            name='nomor_dipa',
            field=models.CharField(default='027.01.1.440140/2021', max_length=500),
        ),
        migrations.AlterField(
            model_name='kontrak',
            name='tanggal_dipa',
            field=models.DateField(default='2020-12-31'),
        ),
        migrations.AlterField(
            model_name='penyedia',
            name='alamat_perusahaan',
            field=models.CharField(max_length=500),
        ),
    ]
