# Generated by Django 3.1.1 on 2021-06-02 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manajemen_kontrak', '0015_pemeriksaanbarang_item_pekerjaan'),
    ]

    operations = [
        migrations.AddField(
            model_name='pemeriksaanbarang',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
