# Generated by Django 3.1.1 on 2021-05-02 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_kontrak', '0015_auto_20210502_1150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='penyedia',
            old_name='direktur_utama',
            new_name='direktur',
        ),
    ]
