# Generated by Django 3.1.1 on 2021-05-02 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_kontrak', '0016_auto_20210502_1152'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Penyedia',
        ),
    ]
