# Generated by Django 3.1.1 on 2021-06-02 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_kontrak', '0016_pemeriksaanbarang_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pemeriksaanbarang',
            old_name='user',
            new_name='user_pemeriksa',
        ),
    ]
