# Generated by Django 3.1.1 on 2021-06-02 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_kontrak', '0017_auto_20210602_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='pemeriksaanbarang',
            name='judul_pemeriksaan',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='useradmin',
            name='profil_pic',
            field=models.ImageField(blank=True, default='avatar.jpeg', null=True, upload_to='profilepics'),
        ),
    ]
