# Generated by Django 3.1.1 on 2021-05-02 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_kontrak', '0017_delete_penyedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Penyedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_perusahaan', models.CharField(max_length=300)),
                ('alamat_perusahaan', models.CharField(max_length=500)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('npwp_perusahaan', models.CharField(max_length=15)),
                ('nomor_rekening', models.CharField(max_length=100)),
                ('bank', models.CharField(max_length=200)),
                ('direktur', models.CharField(max_length=300)),
                ('no_telepon', models.CharField(blank=True, max_length=50, null=True)),
                ('no_hp', models.CharField(blank=True, max_length=50, null=True)),
                ('keterangan', models.TextField()),
            ],
        ),
    ]
