# Generated by Django 3.1.1 on 2021-06-02 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_kontrak', '0018_auto_20210602_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useradmin',
            name='profil_pic',
            field=models.ImageField(blank=True, default='profilepics/avatar.jpeg', null=True, upload_to='profilepics'),
        ),
    ]
