# Generated by Django 3.1.1 on 2021-05-02 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_kontrak', '0018_penyedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penyedia',
            name='keterangan',
            field=models.TextField(blank=True, null=True),
        ),
    ]
