# Generated by Django 3.1.1 on 2021-05-02 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_kontrak', '0019_auto_20210502_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penyedia',
            name='bank',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='penyedia',
            name='nomor_rekening',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='penyedia',
            name='npwp_perusahaan',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
