# Generated by Django 3.1.1 on 2021-06-03 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_kontrak', '0020_remove_pemeriksaanbarang_judul_pemeriksaan'),
        ('manajemen_kontrak', '0006_auto_20210603_0828'),
    ]

    operations = [
    ]
