# Generated by Django 3.1.1 on 2021-05-02 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_kontrak', '0020_auto_20210502_1248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barang',
            old_name='nama_barang',
            new_name='nama_barang_atau_item_pekerjaan',
        ),
        migrations.AlterField(
            model_name='barang',
            name='satuan',
            field=models.CharField(choices=[('unit', 'unit'), ('buah', 'buah'), ('ls', 'ls'), ('hari', 'hari'), ('minggu', 'minggu'), ('bulan', 'bulan'), ('tahun', 'tahun')], max_length=100),
        ),
    ]
