# Generated by Django 3.1.1 on 2021-05-02 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_kontrak', '0021_auto_20210502_1252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barang',
            old_name='nama_barang_atau_item_pekerjaan',
            new_name='nama_barang',
        ),
    ]
