# Generated by Django 3.1.1 on 2021-05-02 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_kontrak', '0022_auto_20210502_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='kontrak',
            name='dibuat_oleh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manajemen_kontrak.useradmin'),
        ),
    ]
