# Generated by Django 3.1.1 on 2021-05-02 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_kontrak', '0023_kontrak_dibuat_oleh'),
    ]

    operations = [
        migrations.AddField(
            model_name='kontrak',
            name='barang',
            field=models.ManyToManyField(to='manajemen_kontrak.Barang'),
        ),
    ]
