# Generated by Django 3.1.1 on 2021-05-02 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_kontrak', '0024_kontrak_barang'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Kontrak',
        ),
    ]
