# Generated by Django 3.1.1 on 2021-06-03 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_kontrak', '0025_auto_20210603_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='kontrak',
            name='bagian',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='manajemen_kontrak.bagian'),
        ),
    ]
