# Generated by Django 3.1.1 on 2021-05-02 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_kontrak', '0029_lampirankontrak'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lampirankontrak',
            unique_together={('kontrak', 'barang', 'penyedia')},
        ),
    ]
