# Generated by Django 3.1.1 on 2021-05-02 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_kontrak', '0030_auto_20210502_1357'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LampiranKontrak',
        ),
    ]
