# Generated by Django 3.1.1 on 2021-05-02 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_kontrak', '0033_auto_20210502_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kontrak',
            name='barang',
        ),
    ]
