# Generated by Django 3.1.1 on 2021-05-02 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_kontrak', '0034_remove_kontrak_barang'),
    ]

    operations = [
        migrations.AddField(
            model_name='kontrak',
            name='dokumen_pengadaan',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='files/'),
        ),
    ]
