# Generated by Django 3.1.1 on 2021-05-02 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_kontrak', '0035_kontrak_dokumen_pengadaan'),
    ]

    operations = [
        migrations.AddField(
            model_name='kontrak',
            name='keterangan',
            field=models.TextField(blank=True, null=True),
        ),
    ]
