# Generated by Django 3.1.1 on 2021-05-02 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_kontrak', '0036_kontrak_keterangan'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoItemPekerjaan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_foto', models.ImageField(blank=True, default='profile.png', null=True, upload_to='')),
                ('item_pekerjaan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manajemen_kontrak.lampirankontrak')),
            ],
        ),
    ]
