# Generated by Django 3.1.1 on 2021-05-03 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_kontrak', '0038_tandaterimadistribusi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tandaterimadistribusi',
            name='kuantitas',
        ),
        migrations.RemoveField(
            model_name='tandaterimadistribusi',
            name='barang',
        ),
        migrations.AddField(
            model_name='tandaterimadistribusi',
            name='barang',
            field=models.ManyToManyField(to='manajemen_kontrak.Barang'),
        ),
    ]
