# Generated by Django 3.1.1 on 2021-05-03 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_kontrak', '0039_auto_20210503_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='tandaterimadistribusi',
            name='kuantitas',
            field=models.ManyToManyField(to='manajemen_kontrak.LampiranKontrak'),
        ),
    ]
