# Generated by Django 3.1.1 on 2021-05-03 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_kontrak', '0040_tandaterimadistribusi_kuantitas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tandaterimadistribusi',
            name='kuantitas',
        ),
    ]
