# Generated by Django 3.1.1 on 2021-05-03 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_kontrak', '0042_remove_tandaterimadistribusi_barang'),
    ]

    operations = [
        migrations.CreateModel(
            name='LampiranTandaTerima',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kuantitas', models.IntegerField()),
                ('barang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manajemen_kontrak.barang')),
                ('nomor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manajemen_kontrak.tandaterimadistribusi')),
            ],
        ),
    ]
