# Generated by Django 3.1.1 on 2021-05-03 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_kontrak', '0044_auto_20210503_0900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tandaterimadistribusi',
            name='kondisi',
        ),
        migrations.AlterField(
            model_name='tandaterimadistribusi',
            name='nomor_tanda_terima',
            field=models.CharField(default='5880/WVZIM5Sm', max_length=100),
        ),
    ]
