# Generated by Django 3.1.1 on 2021-05-03 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_kontrak', '0045_auto_20210503_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='lampirantandaterima',
            name='kondisi',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tandaterimadistribusi',
            name='nomor_tanda_terima',
            field=models.CharField(default='1423/dGnKnuHE', max_length=100),
        ),
    ]
