# Generated by Django 3.1.1 on 2021-05-03 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_kontrak', '0046_auto_20210503_0927'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lampirantandaterima',
            old_name='nomor',
            new_name='nomor_tanda_terima',
        ),
        migrations.AlterField(
            model_name='tandaterimadistribusi',
            name='nomor_tanda_terima',
            field=models.CharField(default='4570/ZJ8FbxTw', max_length=100),
        ),
    ]
