# Generated by Django 3.1.1 on 2021-05-03 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_kontrak', '0047_auto_20210503_0939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barang',
            old_name='keterangan',
            new_name='spesifikasi_dan_gambar',
        ),
        migrations.RemoveField(
            model_name='barang',
            name='spesifikasi',
        ),
        migrations.AlterField(
            model_name='tandaterimadistribusi',
            name='nomor_tanda_terima',
            field=models.CharField(default='6224/HA9FPAux', max_length=100),
        ),
    ]
