# Generated by Django 3.1.1 on 2021-05-04 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_kontrak', '0048_auto_20210503_1313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barang',
            name='spesifikasi_dan_gambar',
        ),
        migrations.AlterField(
            model_name='tandaterimadistribusi',
            name='nomor_tanda_terima',
            field=models.CharField(default='3822/PQW85rkX', max_length=100),
        ),
    ]
