# Generated by Django 3.1.1 on 2021-05-04 01:40

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manajemen_kontrak', '0052_auto_20210504_0840'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_barang', models.CharField(blank=True, max_length=500, null=True)),
                ('merk', models.CharField(blank=True, max_length=200, null=True)),
                ('tipe', models.CharField(blank=True, max_length=200, null=True)),
                ('satuan', models.CharField(choices=[('unit', 'unit'), ('buah', 'buah'), ('ls', 'ls'), ('hari', 'hari'), ('minggu', 'minggu'), ('bulan', 'bulan'), ('tahun', 'tahun')], max_length=100)),
                ('spesifikasi_dan_gambar', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Kontrak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_dipa', models.CharField(default='027.01.1.440140/2021', max_length=500)),
                ('tanggal_dipa', models.DateField(default='2020-12-31')),
                ('nomor_kontrak', models.CharField(max_length=200)),
                ('judul_kontrak', models.CharField(max_length=500)),
                ('tanggal_kontrak', models.DateField(default=datetime.datetime.now)),
                ('tanggal_berakhir_kontrak', models.DateField(default=datetime.datetime.now)),
                ('kode_kegiatan_output_akun', models.CharField(default='2228 / 995 / 532111', max_length=50)),
                ('jenis_pekerjaan', models.CharField(choices=[('Pengadaan Barang', 'Pengadaan Barang'), ('Pekerjaan Konstruksi', 'Pekerjaan Konstruksi'), ('Jasa konsultan', 'Jasa konsultan'), ('Jasa lainnya', 'Jasa lainnya')], default='pengadaan barang', max_length=100)),
                ('bentuk_kontrak', models.CharField(choices=[('Surat Perjanjian (kontrak)', 'Surat Perjanjian (kontrak)'), ('Surat Perintah Kerja', 'Surat Perintah Kerja'), ('Kuitansi', 'Kuitansi'), ('Surat Pesanan', 'Surat Pesanan'), ('Bukti Pembelian', 'Bukti Pembelian')], default='Surat Perintah Kerja', max_length=100)),
                ('nilai_kontrak_terbilang', models.CharField(blank=True, max_length=200, null=True)),
                ('cara_pembayaran', models.CharField(choices=[('Bulanan', 'Bulanan'), ('Bertahap/Termin', 'Bertahap/Termin'), ('Sekaligus', 'Sekaligus')], default='Sekaligus', max_length=200)),
                ('ketentuan_sanksi', models.CharField(blank=True, default='Denda 1 ‰ untuk setiap hari keterlambatan dari biaya / harga keseluruhan (sebelum PPn)', max_length=500, null=True)),
                ('dokumen_pengadaan', models.FileField(blank=True, max_length=255, null=True, upload_to='files/')),
                ('keterangan', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Penyedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_perusahaan', models.CharField(max_length=300)),
                ('alamat_perusahaan', models.CharField(max_length=500)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('npwp_perusahaan', models.CharField(blank=True, max_length=15, null=True)),
                ('nomor_rekening', models.CharField(blank=True, max_length=100, null=True)),
                ('bank', models.CharField(blank=True, max_length=200, null=True)),
                ('direktur', models.CharField(max_length=300)),
                ('no_telepon', models.CharField(blank=True, max_length=50, null=True)),
                ('no_hp', models.CharField(blank=True, max_length=50, null=True)),
                ('keterangan', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('no_hp', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('profil_pic', models.ImageField(blank=True, default='profile.png', null=True, upload_to='')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TandaTerimaDistribusi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_tanda_terima', models.CharField(default='2405/mhqwOPaP', max_length=100)),
                ('tanggal_terima', models.DateField(default=datetime.datetime.now)),
                ('peruntukan', models.CharField(blank=True, max_length=250, null=True)),
                ('yang_menyerahkan', models.CharField(blank=True, max_length=200, null=True)),
                ('yang_menerima', models.CharField(blank=True, max_length=150, null=True)),
                ('kontrak', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manajemen_kontrak.kontrak')),
            ],
        ),
        migrations.CreateModel(
            name='LampiranTandaTerima',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kuantitas', models.IntegerField()),
                ('kondisi', models.CharField(blank=True, max_length=200, null=True)),
                ('barang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manajemen_kontrak.barang')),
                ('nomor_tanda_terima', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manajemen_kontrak.tandaterimadistribusi')),
            ],
        ),
        migrations.CreateModel(
            name='LampiranKontrak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kuantitas', models.IntegerField()),
                ('harga_satuan', models.DecimalField(decimal_places=2, max_digits=15)),
                ('barang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manajemen_kontrak.barang')),
                ('nomor_kontrak', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manajemen_kontrak.kontrak')),
            ],
            options={
                'unique_together': {('barang',)},
            },
        ),
        migrations.AddField(
            model_name='kontrak',
            name='Penyedia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manajemen_kontrak.penyedia'),
        ),
        migrations.AddField(
            model_name='kontrak',
            name='dibuat_oleh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manajemen_kontrak.useradmin'),
        ),
        migrations.CreateModel(
            name='FotoItemPekerjaan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_foto', models.ImageField(blank=True, default='profile.png', null=True, upload_to='')),
                ('item_pekerjaan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manajemen_kontrak.lampirankontrak')),
            ],
        ),
    ]
