# Generated by Django 3.1.1 on 2021-05-04 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_kontrak', '0055_auto_20210504_0851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barang',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='barang',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='barang',
            name='modified_date',
        ),
        migrations.AlterField(
            model_name='tandaterimadistribusi',
            name='nomor_tanda_terima',
            field=models.CharField(default='3381/kt3y01s4', max_length=100),
        ),
    ]
