# Generated by Django 3.1.1 on 2021-05-04 02:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_kontrak', '0057_auto_20210504_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barang',
            name='created_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='barang',
            name='modified_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='tandaterimadistribusi',
            name='nomor_tanda_terima',
            field=models.CharField(default='9496/27KYYQQ2', max_length=100),
        ),
    ]
