# Generated by Django 3.1.1 on 2021-05-04 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_kontrak', '0060_auto_20210504_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penyedia',
            name='npwp_perusahaan',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tandaterimadistribusi',
            name='nomor_tanda_terima',
            field=models.CharField(default='1046/pJLzEtDP', max_length=100),
        ),
    ]
