# Generated by Django 3.1.1 on 2021-05-04 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_kontrak', '0061_auto_20210504_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='kontrak',
            name='status',
            field=models.CharField(choices=[('Final', 'Final'), ('Draft', 'Draft')], default='Final', max_length=100),
        ),
        migrations.AlterField(
            model_name='tandaterimadistribusi',
            name='nomor_tanda_terima',
            field=models.CharField(default='2310/MzvzWACH', max_length=100),
        ),
    ]
