# Generated by Django 3.1.1 on 2021-05-04 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_kontrak', '0062_auto_20210504_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tandaterimadistribusi',
            name='nomor_tanda_terima',
            field=models.CharField(default='4293/uMIMINqL', max_length=100),
        ),
    ]
