# Generated by Django 3.1.1 on 2021-05-04 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_kontrak', '0063_auto_20210504_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='kontrak',
            name='tahun_anggaran',
            field=models.CharField(choices=[('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025')], default=2021, max_length=4),
        ),
        migrations.AlterField(
            model_name='tandaterimadistribusi',
            name='nomor_tanda_terima',
            field=models.CharField(default='7823/dBQdW38X', max_length=100),
        ),
    ]
