# Generated by Django 3.1.1 on 2021-05-04 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_kontrak', '0064_auto_20210504_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tandaterimadistribusi',
            name='nomor_tanda_terima',
            field=models.CharField(default='1475/tADQkxom', max_length=100),
        ),
    ]
