# Generated by Django 3.1.1 on 2021-05-04 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_kontrak', '0065_auto_20210504_1034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kontrak',
            old_name='Penyedia',
            new_name='penyedia',
        ),
        migrations.AlterField(
            model_name='kontrak',
            name='nomor_dipa',
            field=models.CharField(default='027.01.1.440140/2020', max_length=500),
        ),
        migrations.AlterField(
            model_name='kontrak',
            name='nomor_kontrak',
            field=models.CharField(default='.../1.5/PL.02.01/5/2021', max_length=200),
        ),
        migrations.AlterField(
            model_name='kontrak',
            name='tahun_anggaran',
            field=models.CharField(choices=[('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025'), ('2026', '2026'), ('2027', '2027'), ('2028', '2028'), ('2029', '2029'), ('2030', '2030')], default=2021, max_length=4),
        ),
        migrations.AlterField(
            model_name='tandaterimadistribusi',
            name='nomor_tanda_terima',
            field=models.CharField(default='1004/bvbv60oz', max_length=100),
        ),
    ]
