# Generated by Django 3.1.1 on 2021-05-04 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_kontrak', '0066_auto_20210504_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='kontrak',
            name='nilai_kontrak',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tandaterimadistribusi',
            name='nomor_tanda_terima',
            field=models.CharField(default='7041/30cllyrH', max_length=100),
        ),
    ]
