# Generated by Django 3.1.1 on 2021-05-05 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_kontrak', '0067_auto_20210504_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kontrak',
            name='dibuat_oleh',
        ),
        migrations.AddField(
            model_name='kontrak',
            name='created_by',
            field=models.IntegerField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='kontrak',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='kontrak',
            name='modified_by',
            field=models.IntegerField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='kontrak',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='tandaterimadistribusi',
            name='nomor_tanda_terima',
            field=models.CharField(default='2495/4xXwxiYx', max_length=100),
        ),
    ]
