# Generated by Django 3.1.1 on 2021-05-07 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_kontrak', '0070_auto_20210506_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='lampirankontrak',
            name='catatan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tandaterimadistribusi',
            name='nomor_tanda_terima',
            field=models.CharField(default='9017/KYImTg5x', max_length=100),
        ),
    ]
