# Generated by Django 3.1.1 on 2021-05-07 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_kontrak', '0071_auto_20210507_0826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lampirankontrak',
            name='catatan',
        ),
        migrations.AlterField(
            model_name='tandaterimadistribusi',
            name='nomor_tanda_terima',
            field=models.CharField(default='1173/jKttflwX', max_length=100),
        ),
    ]
