# Generated by Django 3.1.1 on 2021-05-07 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_kontrak', '0072_auto_20210507_0832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kontrak',
            name='nilai_kontrak',
        ),
        migrations.RemoveField(
            model_name='kontrak',
            name='nilai_kontrak_terbilang',
        ),
        migrations.AlterField(
            model_name='tandaterimadistribusi',
            name='nomor_tanda_terima',
            field=models.CharField(default='3134/8FGLpCTS', max_length=100),
        ),
    ]
