# Generated by Django 3.1.1 on 2021-05-07 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_kontrak', '0073_auto_20210507_1053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fotoitempekerjaan',
            name='item_pekerjaan',
        ),
        migrations.AlterField(
            model_name='tandaterimadistribusi',
            name='nomor_tanda_terima',
            field=models.CharField(default='7870/c6uEi4sT', max_length=100),
        ),
    ]
