# Generated by Django 3.1.1 on 2021-05-07 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_kontrak', '0074_auto_20210507_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='lampirankontrak',
            name='foto_pekerjaan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manajemen_kontrak.fotoitempekerjaan'),
        ),
        migrations.AlterField(
            model_name='tandaterimadistribusi',
            name='nomor_tanda_terima',
            field=models.CharField(default='1473/XZvDxTNB', max_length=100),
        ),
    ]
