# Generated by Django 3.1.1 on 2021-05-07 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_kontrak', '0075_auto_20210507_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lampirankontrak',
            name='foto_pekerjaan',
        ),
        migrations.AlterField(
            model_name='tandaterimadistribusi',
            name='nomor_tanda_terima',
            field=models.CharField(default='9096/rTmIweSe', max_length=100),
        ),
    ]
