# Generated by Django 3.1.1 on 2021-05-07 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_kontrak', '0077_auto_20210507_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tandaterimadistribusi',
            name='nomor_tanda_terima',
            field=models.CharField(default='9177/rQaY2JcF', max_length=100),
        ),
        migrations.CreateModel(
            name='FotoItemPekerjaan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_foto', models.ImageField(blank=True, default='profile.png', null=True, upload_to='')),
                ('item_pekerjaan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manajemen_kontrak.lampirankontrak')),
            ],
        ),
    ]
