# Generated by Django 3.1.1 on 2021-05-08 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_kontrak', '0078_auto_20210507_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lampirankontrak',
            name='barang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manajemen_kontrak.barang'),
        ),
        migrations.AlterField(
            model_name='tandaterimadistribusi',
            name='nomor_tanda_terima',
            field=models.CharField(default='4096/LoVhUxyt', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='lampirankontrak',
            unique_together=set(),
        ),
    ]
