# Generated by Django 3.1.1 on 2021-05-08 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_kontrak', '0080_auto_20210508_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kontrak',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manajemen_kontrak.useradmin'),
        ),
        migrations.AlterField(
            model_name='tandaterimadistribusi',
            name='nomor_tanda_terima',
            field=models.CharField(default='2586/djGk2j5R', max_length=100),
        ),
    ]
