# Generated by Django 3.1.1 on 2021-05-08 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_kontrak', '0082_auto_20210508_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tandaterimadistribusi',
            name='nomor_tanda_terima',
            field=models.CharField(default='6688/WczJFd5L', max_length=100),
        ),
    ]
