# Generated by Django 3.1.1 on 2021-05-10 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_kontrak', '0083_auto_20210508_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotoitempekerjaan',
            name='file_foto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='tandaterimadistribusi',
            name='nomor_tanda_terima',
            field=models.CharField(default='1371/FOvR4yNc', max_length=100),
        ),
    ]
