# Generated by Django 3.1.1 on 2021-05-19 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_kontrak', '0084_auto_20210510_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penyedia',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tandaterimadistribusi',
            name='nomor_tanda_terima',
            field=models.CharField(default='4232/w0VZlzlZ', max_length=100),
        ),
        migrations.AlterField(
            model_name='useradmin',
            name='email',
            field=models.EmailField(max_length=200),
        ),
    ]
