# Generated by Django 3.1.1 on 2021-05-19 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_kontrak', '0085_auto_20210519_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lampirankontrak',
            name='harga_satuan',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tandaterimadistribusi',
            name='nomor_tanda_terima',
            field=models.CharField(default='3703/0AkVF9JV', max_length=100),
        ),
    ]
