# Generated by Django 3.1.1 on 2021-05-19 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_kontrak', '0087_auto_20210519_1059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tandaterimadistribusi',
            name='kontrak',
        ),
        migrations.RemoveField(
            model_name='tandaterimadistribusi',
            name='nomor_tanda_terima',
        ),
        migrations.RemoveField(
            model_name='tandaterimadistribusi',
            name='peruntukan',
        ),
        migrations.RemoveField(
            model_name='tandaterimadistribusi',
            name='tanggal_terima',
        ),
        migrations.RemoveField(
            model_name='tandaterimadistribusi',
            name='yang_menerima',
        ),
        migrations.RemoveField(
            model_name='tandaterimadistribusi',
            name='yang_menyerahkan',
        ),
        migrations.AddField(
            model_name='tandaterimadistribusi',
            name='tanda_terima',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='LampiranTandaTerima',
        ),
    ]
