# Generated by Django 3.1.1 on 2021-05-19 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_kontrak', '0088_auto_20210519_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='lampirankontrak',
            name='tanda_terima',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manajemen_kontrak.tandaterimadistribusi'),
        ),
    ]
