# Generated by Django 3.1.1 on 2021-05-19 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_kontrak', '0089_lampirankontrak_tanda_terima'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotoitempekerjaan',
            name='item_pekerjaan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manajemen_kontrak.lampirankontrak'),
        ),
    ]
