# Generated by Django 3.1.1 on 2021-05-19 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manajemen_kontrak', '0091_auto_20210519_1121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lampirankontrak',
            old_name='tanda_terima',
            new_name='file_tanda_terima',
        ),
        migrations.AlterField(
            model_name='useradmin',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
    ]
