# Generated by Django 3.1.1 on 2021-05-19 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_kontrak', '0093_auto_20210519_1151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tandaterimadistribusi',
            old_name='tanda_terima',
            new_name='file_tanda_terima',
        ),
    ]
