# Generated by Django 3.1.1 on 2021-05-19 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_kontrak', '0094_auto_20210519_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lampirankontrak',
            name='file_tanda_terima',
        ),
        migrations.AddField(
            model_name='tandaterimadistribusi',
            name='lampiran_kontrak',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manajemen_kontrak.lampirankontrak'),
        ),
    ]
